version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile # Path to your FastAPI backend Dockerfile inside the `database` directory
    ports:
      - "8000:8000" # Map the port to access the API
    environment:
      - operating_system=mommck
      - ENVIRONMENT=raspi
    volumes:
      - ./data/images:/app/data
    devices:  
      - "/dev/i2c-1:/dev/i2c-1" 
      - "/dev/gpiomem:/dev/gpiomem" 
      - "/dev/vchiq:/dev/vchiq"
    depends_on:
      - database
    privileged: true
    restart: always

  database:
    build:
      context: ./database
      dockerfile: Dockerfile # Path to your FastAPI backend Dockerfile inside the `database` directory
    ports:
      - "6000:6000" # Map the port to access the API
    environment:
      - operating_system=mock
    volumes:
      - ./data/sensor_data:/app/data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Path to your frontend Dockerfile inside the `frontend` directory
    ports:
      - "3000:3000" # Map the port to access the frontend
    environment:
      - REACT_APP_API_HOSTNAME=http://192.168.1.41:8000
    restart: always
  # volumes:
  # data:
